version: '3'
services:
  backend:
    build: .
    ports:
      - "8082:8080"
    container_name: seniors-green
    environment:
      - REDIS_HOST = 3.39.139.19
      - REDIS_PORT = 6379
volumes:
  redis_data: